# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4dcd8dcbf696285f0eba9377bf2febddcd56aa5b4994b803e9d3378c8238188376bcf3aabfffc33f72edbe93e33c76e98f51088da2d128845440efa399b1c12f

test:
  secret_key_base: 9cd20aaccc79560e025bb166ef45d9b800e65ffda540e811af3027a00973a3c920cedb89e2a918904ad14ed698e26ecba8396640c5f4a53eef350b688b8c5bce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
